import {
	r,//没有token校验
	a,//有token校验
	n,
} from "./apiBase";
import global from '../utils/global.js';
const path=global.path
const api = {
	mini:{
		getOpenId:r(`GET ${path}wechat/getOpenId`),
		getBarCode:r(`GET ${path}wechat/getBarCode`),
		updateXcxPhoneNumber:r(`GET ${path}systemUser/updateXcxPhoneNumber`),
	},
	home:{
		homeBanner:r(`GET ${path}lunbo/getListAll`),
		homeMenu:r(`GET ${path}homeMenu/getListAll`),
		homeArea:r(`GET ${path}specialArea/getListAll`),
	},
	classify:{
		getData:r(`GET ${path}categories/getListByType`)
	},
	user: {
		login: r(`POST ${path}login/login`),
		loginBySmsCode: r(`POST ${path}login/loginBySmsCode`),
		createSingleUserByWeChat: r(`POST ${path}login/createSingleUserByWeChat`),
		updateUserRecommendId: r(`POST ${path}systemUser/updateUserRecommendId`),
		getDbUserInfo:a(`POST ${path}login/getDbUserInfo`),
		uploadHeadPic:a(`POST ${path}systemUser/uploadHeadPic`),
		updateSystemUserHeadImage:a(`POST ${path}systemUser/updateSystemUserHeadImage`),
		getBalanceList:a(`GET ${path}balance/getInfoByUserId`),
		getBalanceAList:a(`GET ${path}balanceA/getInfoByUserId`),
		getBalanceTopList:a(`GET ${path}balance/getListTop50`),
		getWithdrawList:a(`GET ${path}balanceWithdraw/getList`),
		getWithdrawAList:a(`GET ${path}balanceWithdrawA/getList`),
		getBankAccount:a(`GET ${path}bankAccount/getInfoByUserId`),
		updateSystemUserByToken:a(`POST ${path}systemUser/updateSystemUserByToken`),
		updateNameAndHeadImageByToken:a(`POST ${path}systemUser/updateNameAndHeadImageByToken`),
		updateWithdrawalError:a(`POST ${path}balanceWithdraw/updateWithdrawalError`),
		updateWithdrawalAError:a(`POST ${path}balanceWithdrawA/updateWithdrawalError`),
		forgetPassword:a(`POST ${path}systemUser/updateResetPassWord`),
		register:a(`POST ${path}systemUser/saveSystemUserByRecommendCode`),
		updateSystemUserPassWord:a(`POST ${path}systemUser/updateSystemUserPassWord`),
		updateNewPhone:a(`POST ${path}systemUser/updateNewPhone`),
		updateBindPhone:a(`POST ${path}systemUser/updateBindPhone`),
		saveBankAccount:a(`POST ${path}bankAccount/saveBankAccount`),
		updateBankAccount:a(`POST ${path}bankAccount/updateBankAccount`),
		getScanDataInfo:a(`GET ${path}systemUser/getScanDataInfo`),
		getWithdrawalAmount:a(`GET ${path}globleSetting/getWithdrawalAmount`),
		getIntegralList:a(`GET ${path}integral/getInfoByUserId`),
		giftIntegral:a(`POST ${path}integral/giftIntegral`),
		getMessageList:a(`GET ${path}sysMessage/getListToApi`),
		getMessageDetail:a(`GET ${path}sysMessage/getInfoById`),
		messageIsRead:a(`POST ${path}sysMessage/updateIsRead`),
		saveBalanceWithdraw:a(`POST ${path}balanceWithdraw/saveBalanceWithdraw`),
		saveBalanceWithdrawA:a(`POST ${path}balanceWithdrawA/saveBalanceWithdrawA`),
		saveBalanceDetailsToReplacement:a(`POST ${path}balanceDetails/saveBalanceDetailsToReplacement`),
		getEntityShop:a(`GET ${path}entityShop/getInfoByUserId`),
		getEntityShopList:a(`GET ${path}entityShop/getListByEntityShopId`),
		getUserLevel:a(`GET ${path}userLevelRelation/getInfoByUserId`),
		getSystemMessage:a(`GET ${path}sysMessage/getListToSystem`),
		updateSystemIsRead:a(`POST ${path}sysMessage/updateSystemIsRead`),
		saveTransferInfo:a(`POST ${path}userTransferInfo/saveInfo`),
		getListUserAndUserLevel:a(`GET ${path}systemUser/getListUserAndUserLevel`),
		getListUserAndUserLevelByTransfer:a(`GET ${path}systemUser/getListUserAndUserLevelByTransfer`),
		getSystemUserById:a(`GET ${path}systemUser/getSystemUserById`),
		getListByTransfer:a(`GET ${path}systemUser/getListByTransfer`),
		getUserTeamValueDetails:a(`GET ${path}userTeamValueDetails/getList`),
		getPosRecordMainById:a(`GET ${path}posRecordMain/getInfoByUserId`),
		getTotalAmountByPosAndTotalAmountByBalanceAndUserQty:a(`GET ${path}systemUser/getTotalAmountByPosAndTotalAmountByBalanceAndUserQty`),
	},
	pay:{
		getPayDataInfo:a(`GET ${path}systemRequestPayData/getPayDataInfo`),
		getPayPropertyDataInfo:a(`GET ${path}systemRequestPayData/getPayPropertyDataInfo`),
	},
	globleSetting:{
		getInfoByNumber:a(`GET ${path}globleSetting/getInfoByNumber`),
	},
	sms:{
		getVerifyCode:a(`GET ${path}systemSmsVerification/getVerifyCode`),
	},
	goods:{
		list:r(`GET ${path}shopGoods/getListToApi`),
		limitList:r(`GET ${path}shopGoods/getListLimitByToApi`),
		integralList:r(`GET ${path}shopGoods/getListByIntegralGoods`),
		detail:r(`GET ${path}shopGoods/getInfoById`),
		entityShopDetail:r(`GET ${path}entityShop/getInfoByFlagData`),
		goodsStatisticsMain:r(`GET ${path}goodsStatisticsMain/getInfoByGoodsId`),
		getGoodsSetting:r(`GET ${path}goodsSetting/getInfoByGoodsId`),
		getOffLineData:r(`GET ${path}offlineShop/getList`),
		getDate:r(`GET ${path}userLevel/getDate`),
		getUserLevelPrice:r(`GET ${path}goodsUserLevelRelation/getListByGoodsId`),
	},
	cart:{
		num:a(`GET ${path}simpleShopCars/getStatistics`),
		list:a(`GET ${path}simpleShopCars/getListByUserId`),
		totalPrice:a(`GET ${path}simpleShopCars/calcTotalPrice`),
		deleteById:a(`GET ${path}simpleShopCars/deleteById`),
		deleteAll:a(`GET ${path}simpleShopCars/deleteAll`),
		add:a(`POST ${path}simpleShopCars/saveSimpleShopCars`),
		updateIsChecked:a(`POST ${path}simpleShopCars/updateIsChecked`),
		updateAllIsChecked:a(`POST ${path}simpleShopCars/updateAllIsChecked`),
		updateShopCars:a(`POST ${path}simpleShopCars/updateSimpleShopCars`),
	},
	shop:{
		detail:a(`GET ${path}shop/getInfoById`),
	},
	address:{
		list:a(`GET ${path}address/getListByUserId`),
		deleteById:a(`GET ${path}address/deleteById`),
		updateDefault:a(`POST ${path}address/updateDefault`),
		saveAddress:a(`POST ${path}address/saveAddress`),
		updateAddress:a(`POST ${path}address/updateAddress`),
	},
	confirm:{
		rightNowPreBuildorder:a(`GET ${path}goodsOrder/rightNowPreBuildorder`),//立即下单预订单
		advanceOrder:a(`GET ${path}goodsOrder/advanceOrder`),//购物车预订单
		rightNowBuildOrder:a(`GET ${path}goodsOrder/rightNowBuildOrder`),//立即下单
		buildDepartmentStoreOrder:a(`GET ${path}goodsOrder/buildDepartmentStoreOrder`),//购物车下单
		
		//新的预定单 
		rightNowPreBuildorderNew:a(`POST ${path}goodsOrder/rightNowPreBuildOrderNew`),//立即下单预订单
		advanceOrderNew:a(`POST ${path}goodsOrder/advanceOrderNew`),//购物车预订单
		
		rightNowBuildOrderNew:a(`POST ${path}goodsOrder/rightNowBuildOrderNew`),//立即下单
		buildDepartmentStoreOrderNew:a(`POST ${path}goodsOrder/buildDepartmentStoreOrderNew`),//购物车下单
	},
	order:{
		list:a(`GET ${path}goodsOrder/getListByUserId`),
		detail:a(`GET ${path}goodsOrder/myGoodsOrderDetails`),
		cancel:a(`POST ${path}goodsOrder/userCancleGeneralSelfOrder`),
		complete:a(`POST ${path}goodsOrder/deliveryOverOrder`),
		cancelReturnGoods:a(`POST ${path}goodsOrder/cancelReturnGoods`),
		returnGoods:a(`POST ${path}goodsOrder/returnGoods`),
		refundGoodsAmountWechatNotSend:a(`POST ${path}goodsOrder/refundGoodsAmountWechatNotSend`),
	},
	comment:{
		save:a(`POST ${path}comment/saveComment`),
		goodsList:a(`GET ${path}comment/getListAll`),
		getStatistics:a(`GET ${path}comment/getStatistics`),
		getListByParent:a(`GET ${path}comment/getListByParent`),
		getInfoById:a(`GET ${path}comment/getInfoById`),
		myList:a(`GET ${path}comment/getList`),
		deleteById:a(`GET ${path}comment/deleteById`),
	},
	sign:{
		sign:a(`POST ${path}sign/saveInfo`),
		list:a(`GET ${path}signDetails/getList`),
		getIsSign:a(`GET ${path}signDetails/getIsSign`),
	},
	coupon:{
		center:a(`GET ${path}coupon/getList`),
		list:a(`GET ${path}couponUserRelation/getList`),
		getNeedIntegral:a(`GET ${path}couponUserRelation/getNeedIntegral`),
		save:a(`POST ${path}couponUserRelation/saveInfo`),
		saveInfoBySign:a(`POST ${path}couponUserRelation/saveInfoBySign`),
		getUserCouponList:a(`GET ${path}couponUserRelation/getListByUserId`),
	},
	level:{
		list:a(`GET ${path}userLevel/getList`),
		orderList:a(`GET ${path}userLevelOrder/getList`),
		save:a(`POST ${path}userLevelOrder/saveInfo`),
	},
	globalSetting:{
		info:a(`GET ${path}globleSetting/getInfoByNumber`),
	},
	visit:{
		save:r(`POST ${path}everydayVisitStatistics/saveInfo`),
	},
	freeBack:{
		list:a(`GET ${path}systemFreeBack/getRootList`),
		detail:a(`GET ${path}systemFreeBack/getListByParentId`),
		info:a(`GET ${path}systemFreeBack/getInfoById`),
		save:r(`POST ${path}/systemFreeBack/saveInfo`),
	},
	protocol:{
		getInfoByNumber:a(`GET ${path}systemProtocol/getInfoByNumber`),
	},
	dictionary:{
		info:a(`GET ${path}systemDictionary/getListByParentNumber`),
	},
	news:{
		list:a(`GET ${path}adNews/getListIsEnable`),
		getListTypNumber:a(`GET ${path}adNews/getListTypNumber`),
		getAdNewsById:a(`GET ${path}adNews/getAdNewsById`),
	},
	goodsOrderRefend:{
		updateDelivery:a(`POST ${path}goodsOrderRefend/updateDelivery`),
		saveInfo:a(`POST ${path}goodsOrderRefend/saveInfo`),
		updateInfo:a(`POST ${path}goodsOrderRefend/updateInfo`),
		getInfoByGoodsIdAndType:a(`GET ${path}goodsOrderRefend/getInfoByGoodsIdAndType`),
	},
	simpleGoods:{
		list:a(`GET ${path}simpleGoods/getList`),
		detail:a(`GET ${path}simpleGoods/getInfoById`),
	},
	simpleGoodsOrder:{
		getOrderIsPayStandard:a(`GET ${path}simpleGoodsOrder/getOrderIsPayStandard`),
		rightNowPreBuildOrder:a(`POST ${path}simpleGoodsOrder/rightNowPreBuildOrder`),
		save:a(`POST ${path}simpleGoodsOrder/saveInfo`),
		updateOrderStatus:a(`POST ${path}simpleGoodsOrder/updateOrderStatus`),
		updateOrderReturn:a(`POST ${path}simpleGoodsOrder/updateOrderReturn`),
		updateOrderIsPay:a(`POST ${path}simpleGoodsOrder/updateOrderIsPay`),
		getLogisticInfo:a(`POST ${path}simpleGoodsOrder/getLogisticInfo`),
		list:a(`GET ${path}simpleGoodsOrder/getList`),
		detail:a(`GET ${path}simpleGoodsOrder/getInfoAllById`),
	},
	community:{
		applyList:a(`GET ${path}communityApplyInfo/getListToApi`),
		getMyCommunityRepairList:a(`GET ${path}communityRepairInfo/getListToApi`),
		getListByRepairToApi:a(`GET ${path}communityRepairInfo/getListByRepairToApi`),
		getCommunityRepairItems:a(`GET ${path}communityRepairItemInfo/getListToApi`),
		communityRepairListByParentId:a(`GET ${path}communityRepairInfo/getListByParentId`),
		getMyDealCommunityRepairList:a(`GET ${path}communityRepairInfo/getListByDealUserToApi`),
		getListByUser:a(`GET ${path}communityRepairAdmin/getListByUser`),
		getCntByStatus:a(`GET ${path}communityRepairInfo/getCntByStatus`),
		getCntByRepairAndStatus:a(`GET ${path}communityRepairInfo/getCntByRepairAndStatus`),
		getListToMyArea:a(`GET ${path}communityBaseInfo/getListToMyArea`),
		updateApply:a(`POST ${path}communityApplyInfo/updateInfo`),
		saveApply:a(`POST ${path}communityApplyInfo/saveInfo`),
		getApplyDetail:a(`GET ${path}communityApplyInfo/getInfoById`),
		messageList:a(`GET ${path}communityMessageInfo/getListToApi`),
		messageListByParentId:a(`GET ${path}communityMessageInfo/getListByParentId`),
		getMessageInfo:a(`GET ${path}communityMessageInfo/getInfoById`),
		getCommunityRepairInfo:a(`GET ${path}communityRepairInfo/getInfoById`),
		getParkList:a(`GET ${path}communityParkingInfo/getListIsEnable`),
		getMyHourseListToApi:a(`GET ${path}communityHourseInfo/getListToApi`),
		getAreaList:a(`GET ${path}communityBaseInfo/getList`),
		getListGroupYear:a(`GET ${path}communityPropertyMonth/getListGroupYear`),
		notReadCnt:a(`GET ${path}communityNotifyInfo/notReadCnt`),
		getNotifyListToApi:a(`GET ${path}communityNotifyInfo/getListToApi`),
		getInfoByIdAndUpdateIsRead:a(`GET ${path}communityNotifyInfo/getInfoByIdAndUpdateIsRead`),
		getParkingListGroupYear:a(`GET ${path}communityParkingMonth/getListGroupYear`),
		saveMessage:a(`POST ${path}communityMessageInfo/saveInfo`),
		saveRepairInfo:a(`POST ${path}communityRepairInfo/saveInfo`),
		updateRepairInfoStatus:a(`POST ${path}communityRepairInfo/updateStatus`),
		deleteRepairInfo:a(`POST ${path}communityRepairInfo/deleteById`),
		updateUnbind:a(`POST ${path}communityHourseInfo/updateUnbind`),
		saveCommunityPaymentOrder:a(`POST ${path}communityPaymentOrder/saveInfo`),
		saveParkingPaymentOrder:a(`POST ${path}communityParkingOrder/saveInfo`),
	},
	terminal:{
		save:a(`POST ${path}posUserBind/saveInfo`),
		delete:a(`POST ${path}posUserBind/deleteById`),
		list:a(`GET ${path}posUserBind/getList`),
		recordList:a(`GET ${path}posRecord/getList`),
	},
	globleData:{
		getListByGroupNo:a(`GET ${path}globleData/getListByGroupNo`),
	},
	checkCode:{
		getInfo:a(`GET ${path}checkCode/getInfoByCode`),
	},
	worker:{
		getList:a(`GET ${path}gbWorker/getList`),
		getInfoById:a(`GET ${path}gbWorker/getInfoById`),
		getInfo:a(`GET ${path}gbWorker/getInfoByUserIdOrWorkerTelephone`),
		getListToRecommended:a(`GET ${path}gbWorker/getListToRecommended`),
		saveInfo:a(`POST ${path}gbWorker/saveInfo`),
		updateInfo:a(`POST ${path}gbWorker/updateInfo`),
		updateInfoById:a(`POST ${path}gbWorker/updateInfoById`),
		updateIdentityById:a(`POST ${path}gbWorker/updateIdentityById`),
		updateStateById:a(`POST ${path}gbWorker/updateStateById`),
	},
	workOrder:{
		getList:a(`GET ${path}gbOrder/getList`),
		getEvaluateList:a(`GET ${path}evaluate/getListSettingNormal`),
		getInfoByOrderNo:a(`GET ${path}gbOrder/getInfoByOrderNo`),
		saveInfo:a(`POST ${path}gbOrder/saveInfo`),
		updateToReassignment:a(`POST ${path}gbOrder/updateToReassignment`),
		updateToDispatch:a(`POST ${path}gbOrder/updateToDispatch`),
		updateAbandonedOrder:a(`POST ${path}gbOrder/updateAbandonedOrder`),
		updateComplete:a(`POST ${path}gbOrder/updateComplete`),
		updateCancel:a(`POST ${path}gbOrder/updateCancel`),
		updateWorkMemoAndServiceTime:a(`POST ${path}gbOrder/updateWorkMemoAndServiceTime`),
		updateEvaluate:a(`POST ${path}gbOrder/updateEvaluate`),
		updateToBackFromComplete:a(`POST ${path}gbOrder/updateToBackFromComplete`),
		getDropList:a(`GET ${path}gbDropOrder/getList`),
	},
	appeal:{
		getList:a(`GET ${path}gbAppeal/getList`),
		getInfoById:a(`GET ${path}gbAppeal/getInfoById`),
		getListByParentId:a(`GET ${path}gbAppeal/getListByParentId`),
		saveInfo:a(`POST ${path}gbAppeal/saveInfo`),
	}
}
export default api;
